name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#https://rammusxu.github.io/toolkit/snippets/github-action/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        run: |
          env
          echo "BUILD_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "BUILD_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set Env
        run: |
          echo "BUILD_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "BUILD_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Puuushhh
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: rhvoice-rest
          registry: ghcr.io
          githubOrg: lysyy # optional
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
